//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdsOnSiteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string CarManufacturer { get; set; }
        public string CarMake { get; set; }
        public int CarYear { get; set; }
        public string Color { get; set; }
        public int PassengerSeating { get; set; }
    }
}
